### ISSUE TITLE
Empty Folder

### ISSUE THREAD

**Issue by Marco-9456** [Adolar0042/pwsh-kamyroll#2]
The script is just creating empty folders.
![Screenshot 2022-10-23 135343](https://user-images.githubusercontent.com/41828058/197390649-218f8166-2367-4ac3-bb13-5535f434aafc.png)

**Comment by Adolar0042** [comment]
Just pushed an update that puts errors in `errors.txt` in the same folder as `kamyrollAPI.ps1`
If the error still happens, please send me the `errors.txt` file

On newer versions of the cli, it should just prompt you to update the cli script when you run it, simply accept and run the cli again.

**Comment by Marco-9456** [comment]
> `errors.txt`

hmmm 
the error still happens but it didn't create an `errors.txt` file

**Comment by Adolar0042** [comment]
oops, my bad. I didn't test if that actually worked. The cli should ask you to update again, this time everything should work

**Comment by Marco-9456** [comment]
> oops, my bad. I didn't test if that actually worked. The cli should ask you to update again, this time everything should work

it's Still not creating an errors.txt, but i was abale to copy it this time


```
Invoke-WebRequest : The operation cannot be performed because the resolved placeholder path
"C:\Users\Mohammed.Aldakhil\Desktop\Kamyroll\anime\Hunter x Hunter\1\[en-US] Departure x And x
Friends.ass" does not specify a file.
In C:\Users\Mohammed.Aldakhil\Desktop\Kamyroll\cli.ps1:341 Zeichen:21
+ ...             Invoke-WebRequest -Uri $sub.url -OutFile "$defaultFolder\ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (C:\Users\Mohamm...d x Friends.ass:String) [Invoke-WebRequest
   ], FileNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.InvokeWebRequestCommand 
```

**Comment by Adolar0042** [comment]
Thats a great help, I'll let you know when I have a fix or further information

**Comment by Adolar0042** [comment]
made some changes, please update and try again

**Comment by Marco-9456** [comment]
> made some changes, please update and try again

Here you go 
[errors.txt](https://github.com/Adolar0042/pwsh-kamyroll/files/9846714/errors.txt)

**Comment by Adolar0042** [comment]
I think I found the error; it assumes that the `[ ]` brackets around the subtile locale are wildcards

Once again, please update and test.

**Comment by Marco-9456** [comment]
> I think I found the error; it assumes that the `[ ]` brackets around the subtile locale are wildcards
> 
> Once again, please update and test.

It's working like a charm thanks for your help brother :)

**Comment by Adolar0042** [comment]
Great!
